#!/bin/sh
#
# rfriends3 for ish 2025/08/03
# easy install script
#
echo Ver 1.1
#
cd ~/
apk update
apk upgrade
apk add sudo git
#
rm rfriends3_dev_script.zip
#
rm -rf rfriends3_core
git clone https://github.com/rfriends/rfriends3_core.git
cd rfriends3_core
sh install_ish.sh
#
homedir="/root"
mkdir -p $homedir/usr2/
cat <<EOF > $homedir/rfriends3/config/usrdir.ini
usrdir = "$homedir/usr2/"
tmpdir = "/tmp/"
EOF
#
echo
echo usrdir
cat $homedir/rfriends3/config/usrdir.ini
#
exit
